### ISSUE TITLE
Uncaught Error: Class 'Sourceboat\WordPress\Autoloader\Psr4Loader'

### ISSUE THREAD

**Issue by diginfo** [sourceboat/wp-pug#1]
Hi, not sure if you can help, I just cloned the repo to my plugins folder and get the following error:

```
Error Details
=============
An error of type E_ERROR was caused in line 15 of the file /var/www/wp/sites/www/wp/wp-content/plugins/wp-pug/index.php. Error message: Uncaught Error: Class 'Sourceboat\WordPress\Autoloader\Psr4Loader' not found in /var/www/wp/sites/www/wp/wp-content/plugins/wp-pug/index.php:15
```

I am not running any custom installers and prefer not to, is there a way I can get this to work purely by cloning to the plugins folder ?

Thanks :-)

**Comment by pehbehbeh** [comment]
This package is intended to be installed via Composer. You get all required packages when installing via Composer. The missing dependency in this case is `sourceboat/wp-autoloader`. You can install it manually by adding [sourceboat/wp-autoloader](https://github.com/sourceboat/wp-autoloader) to your plugins folder.
